/** Typed path builders — no string literals in hooks. */
export const ep = {
  auth: {
    register: '/auth/register-restaurant',
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    password: '/auth/me/password',
  },
  restaurant: '/restaurant',
  staff: {
    root: '/staff',
    waiters: '/staff/waiters',
    one: (userId: string) => `/staff/${userId}`,
    password: (userId: string) => `/staff/${userId}/password`,
    status: (userId: string) => `/staff/${userId}/status`,
  },
  tables: {
    root: '/tables',
    my: '/tables/my',
    bulk: '/tables/bulk',
    one: (id: string) => `/tables/${id}`,
    assignment: (id: string) => `/tables/${id}/assignment`,
    assignmentHistory: (id: string) => `/tables/${id}/assignment/history`,
  },
  menu: {
    root: '/menu',
    search: '/menu/search',
    categories: '/menu/categories',
    category: (id: string) => `/menu/categories/${id}`,
    categoryItems: (id: string) => `/menu/categories/${id}/items`,
    items: '/menu/items',
    item: (id: string) => `/menu/items/${id}`,
    availability: (id: string) => `/menu/items/${id}/availability`,
  },
  sessions: {
    root: '/sessions',
    one: (id: string) => `/sessions/${id}`,
    bill: (id: string) => `/sessions/${id}/bill`,
    close: (id: string) => `/sessions/${id}/close`,
    tableHistory: (tableId: string) => `/sessions/table/${tableId}/history`,
  },
  orders: {
    root: '/orders',
    one: (id: string) => `/orders/${id}`,
    status: (id: string) => `/orders/${id}/status`,
    cancel: (id: string) => `/orders/${id}/cancel`,
  },
  kitchen: {
    board: '/kitchen/board',
    counts: '/kitchen/counts',
    start: (id: string) => `/kitchen/orders/${id}/start`,
    complete: (id: string) => `/kitchen/orders/${id}/complete`,
    reopen: (id: string) => `/kitchen/orders/${id}/reopen`,
  },
  reports: {
    summary: '/reports/summary',
    daily: '/reports/daily',
    topItems: '/reports/top-items',
    waiters: '/reports/waiters',
    prepTime: '/reports/prep-time',
    hourly: '/reports/hourly',
  },
} as const;
